### ISSUE TITLE
弹幕切换横竖屏重叠

### ISSUE THREAD

**Issue by Dengfulei** [LevisonNN/LNDanmakuMaster#1]
切换到横屏弹幕会出现重叠问题

**Comment by LevisonNN** [comment]
是在哪个Demo中出现的问题？
目前，只有继承自BaseMoveTrackController的轨道进行了去重叠处理，定点的轨道和随机的轨道是不需要去重叠处理的。
切换横竖屏后，通常需要对轨道的重新进行布局，以普通的横向轨道为例，当竖屏切换到横屏的时候，应该减少轨道的数量，增加每条轨道的长度，通常对这种重置布局有两种处理，1.清掉当前的所有弹幕，从右侧重新播放 2.使用弹幕恢复功能，将该时间点附近的弹幕先清除，再恢复到现有布局中。
所以，横竖屏切换时，轨道的布局如果没有发生改变，弹幕的重叠也不会受到影响，猜测看到的重叠可能是波浪轨道或心形轨道两个轨道之间的重叠，这种重叠是两条轨道的间距较近造成的（距离较近看起来比较紧凑），单个轨道内部是不会重叠的，你可以在Demo中修改轨道间的间距看看是否还重叠。
如果还没有解决你的问题可以加这个qq：805646670
