### ISSUE TITLE
怎么改变轨道上的item的速度，马上更新呢

### ISSUE THREAD

**Issue by Captain-MK** [LevisonNN/LNDanmakuMaster#3]

**Comment by jieruian** [comment]
我也想知道

**Comment by LevisonNN** [comment]
抱歉，看到问题比较晚，有以下两种情况可以考虑：

1.如果你做的是倍速播放：在LNDanmakuClock类里面有个timeScale属性可以设置速度比例，这个速度是直接从Clock中分配的时间进行加速，所以是所有的弹幕都生效的（包括轨道中已有的弹幕和分发队列中的弹幕），设置了这个属性之后，不用操作每个弹幕的时间，就都会加速/减速了。

2.如果你做的是针对与某条特例弹幕进行加速：你需要调整这条弹幕的时间，以横向滑动轨道、速度变为2倍为例，如下调整时间：
A.如果这条弹幕在Dispatcher的队列中，你只需要将TrackTime/danmakuTime都设置为原来的1/2就可以了；
B.如果这条弹幕已经在TrackController（屏幕上）了，你还需要额外调整一下currentTime，例如原弹幕trackTime = 4, danmakuTime = 2，currentTime = 3；设置为：trackTime = 2, danmakuTime = 1, currentTime = 1.5 (因为A情况下currentTime = 0 所以相当于不用调整，所以如果你写一个通用算法来调整的话就是调整三个数值)

如果依然有问题可以在readme的掘金链接上找到我，平时掘金会关注得比较多一些
